# Site settings
author: Jeffrey Royce
title: Blogmaster 3000
header-img: img/home-bg.png
email: jeffte.80@gmail.com
copyright_name: Jeffrey Royce
description: > # this means to ignore newlines until "baseurl:"
  A journey along side me as I become  a Data Scientist.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  anonymousodyssey19

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
